Comp2139-Assignment1/Comp2139-Assignment1/Models/Technicians.cs
using System.ComponentModel.DataAnnotations;

namespace GBCSporting_OJO.Models
{
    public class Technicians
    {
        [Key]
        public int TechnicianId { get; set; }

        [Required (ErrorMessage = "Technician needs a name")]
        public string? TechnicianName { get; set; }

        [Required(ErrorMessage = "Technician needs an email")]
        public string? TechnicianEmail { get; set; }

        [Required(ErrorMessage = "Technician needs a phone number")]
        public string? TechnicianPhone { get; set; }

    }
}

Comp2139-Assignment1/Comp2139-Assignment1/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GBCSporting_OJO.Models;

namespace GBCSporting_OJO.Controllers
{
    public class CustomersController : Controller
    {
        private readonly GBCSporting_OJOContext _context;

        public CustomersController(GBCSporting_OJOContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            ViewData["CustomerCountry"] = new SelectList(_context.Customers, "CustomerCountry", "CustomerCountry");
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,CustomerFirstName,CustomerLastName,CustomerAddress,CustomerCity,CustomerState,CustomerCountry,CustomerEmail,CustomerPhone")] Customers customers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customers);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customers = await _context.Customers.FindAsync(id);
            if (customers == null)
            {
                return NotFound();
            }
            return View(customers);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,CustomerFirstName,CustomerLastName,CustomerAddress,CustomerCity,CustomerState,CustomerCountry,CustomerEmail,CustomerPhone")] Customers customers)
        {
            if (id != customers.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomersExists(customers.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customers);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customers = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customers == null)
            {
                return NotFound();
            }

            return View(customers);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customers = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomersExists(int id)
        {
            return _context.Customers.Any(e => e.CustomerId == id);
        }
    }
}

Comp2139-Assignment1/Comp2139-Assignment1/Controllers/IncidentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GBCSporting_OJO.Models;

namespace GBCSporting_OJO.Controllers
{
    public class IncidentsController : Controller
    {
        private readonly GBCSporting_OJOContext _context;

        public IncidentsController(GBCSporting_OJOContext context)
        {
            _context = context;
        }

        // GET: Incidents
        public async Task<IActionResult> Index()
        {
            var comp2139_Assignment1Context = _context.Incidents.Include(i => i.Customer).Include(i => i.Product).Include(i => i.Technician);
            return View(await comp2139_Assignment1Context.ToListAsync());
        }

        // GET: Incidents/Create
        public IActionResult Create()
        {
            //Values for viewbag on incident form follow: context.model, bindId, valueToBeShowtoUser
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerFirstName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["TechnicianId"] = new SelectList(_context.Technicians, "TechnicianId", "TechnicianName");
            return View();
        }

        // POST: Incidents/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IncidentId,CustomerId,ProductId,IncidentTitle,IncidentDescription,TechnicianId,IncidentDateOpened,IncidentDateClosed")] Incident incident)
        {

            if (ModelState.IsValid)
            {
                _context.Add(incident);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                //in case of error of validation, it calls back the create method with the get items
                return Create();
            }
            
        }

        // GET: Incidents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents.FindAsync(id);
            if (incident == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerFirstName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["TechnicianId"] = new SelectList(_context.Technicians, "TechnicianId", "TechnicianName");
            return View(incident);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IncidentId,CustomerId,ProductId,IncidentTitle,IncidentDescription,TechnicianId,IncidentDateOpened,IncidentDateClosed")] Incident incident)
        {
            if (id != incident.IncidentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incident);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncidentExists(incident.IncidentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerFirstName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["TechnicianId"] = new SelectList(_context.Technicians, "TechnicianId", "TechnicianName");
            return View(incident);
        }

        // GET: Incidents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents
                .Include(i => i.Customer)
                .Include(i => i.Product)
                .Include(i => i.Technician)
                .FirstOrDefaultAsync(m => m.IncidentId == id);
            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }

        // POST: Incidents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var incident = await _context.Incidents.FindAsync(id);
            _context.Incidents.Remove(incident);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IncidentExists(int id)
        {
            return _context.Incidents.Any(e => e.IncidentId == id);
        }
    }
}

Comp2139-Assignment1/Comp2139-Assignment1/Controllers/ProductsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GBCSporting_OJO.Models;

namespace GBCSporting_OJO.Controllers
{
    public class ProductsController : Controller
    {
        private readonly GBCSporting_OJOContext _context;

        public ProductsController(GBCSporting_OJOContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductCode,ProductName,ProductPrice,ProductReleaseDate")] Products products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Create();
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductCode,ProductName,ProductPrice,ProductReleaseDate")] Products products)
        {
            if (id != products.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            _context.Products.Remove(products);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Comp2139-Assignment1/Comp2139-Assignment1/Controllers/TechniciansController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GBCSporting_OJO.Models;

namespace GBCSporting_OJO.Controllers
{
    public class TechniciansController : Controller
    {
        private readonly GBCSporting_OJOContext _context;

        public TechniciansController(GBCSporting_OJOContext context)
        {
            _context = context;
        }

        // GET: Technicians
        public async Task<IActionResult> Index()
        {
            return View(await _context.Technicians.ToListAsync());
        }

        // GET: Technicians/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Technicians/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TechnicianId,TechnicianName,TechnicianEmail,TechnicianPhone")] Technicians technicians)
        {
            if (ModelState.IsValid)
            {
                _context.Add(technicians);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(technicians);
        }

        // GET: Technicians/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var technicians = await _context.Technicians.FindAsync(id);
            if (technicians == null)
            {
                return NotFound();
            }
            return View(technicians);
        }

        // POST: Technicians/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TechnicianId,TechnicianName,TechnicianEmail,TechnicianPhone")] Technicians technicians)
        {
            if (id != technicians.TechnicianId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(technicians);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TechniciansExists(technicians.TechnicianId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(technicians);
        }

        // GET: Technicians/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var technicians = await _context.Technicians
                .FirstOrDefaultAsync(m => m.TechnicianId == id);
            if (technicians == null)
            {
                return NotFound();
            }

            return View(technicians);
        }

        // POST: Technicians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var technicians = await _context.Technicians.FindAsync(id);
            _context.Technicians.Remove(technicians);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TechniciansExists(int id)
        {
            return _context.Technicians.Any(e => e.TechnicianId == id);
        }
    }
}

Comp2139-Assignment1/Comp2139-Assignment1/Views/Shared/_CustomersForm.cshtml
@model GBCSporting_OJO.Models.Customers
@{
    var title = ViewData["Title"] as string;
}

<hr />
<div class="row">
    <div class="col">
        <form asp-action=@ViewData["Title"]>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if(title == "Edit")
            {
                <input type="hidden" asp-for="CustomerId" />
            }

            <br />
            <div class="form-group row">
                <label asp-for="CustomerFirstName" class="col-sm-2 col-form-label">First Name:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerFirstName" class="form-control" />
                    <span asp-validation-for="CustomerFirstName" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="CustomerLastName" class="col-sm-2 col-form-label">Last Name:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerLastName" class="form-control" />
                    <span asp-validation-for="CustomerLastName" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerAddress" class="col-sm-2 col-form-label">Address:</label>
                <div class="col-sm-10">
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerCity" class="col-sm-2 col-form-label">City:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerCity" class="form-control" />
                    <span asp-validation-for="CustomerCity" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerState" class="col-sm-2 col-form-label">State:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerState" class="form-control" />
                    <span asp-validation-for="CustomerState" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerCountry" class="col-sm-2 col-form-label">Country:</label>
                <div class="col-sm-10">
                    @if(title == "Create")
                    {
                        <select asp-for="CustomerCountry" class="form-control" asp-items="@ViewBag.CustomerCountry"></select>
                    }
                    else
                    {
                        <input asp-for="CustomerCountry" class="form-control" />
                    }
                    <span asp-validation-for="CustomerCountry" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerEmail" class="col-sm-2 col-form-label">Email:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerEmail" class="form-control" />
                    <span asp-validation-for="CustomerEmail" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group row">
                <label asp-for="CustomerPhone" class="col-sm-2 col-form-label">Phone:</label>
                <div class="col-sm-10">
                    <input asp-for="CustomerPhone" class="form-control" />
                    <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                </div>
            </div>

             <br />
            <div class="form-group">
                <input type="submit" value="@title" class="btn btn-success" />
                @if(title == "Create")
                {
                 <input type="reset" class="btn btn-danger" />   
                }
            </div>
        </form>
    </div>
</div>

<br />
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to Customers List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comp2139-Assignment1/Comp2139-Assignment1/Views/Shared/_IncidentForm.cshtml
@model GBCSporting_OJO.Models.Incident
@{
    var title = ViewData["Title"] as string;
}

<hr />
<div class="row">
    <div class="col">
        <form asp-action=@ViewData["Title"]>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if(title == "Edit")
            {
                <input type="hidden" asp-for="IncidentId" />
            }

            <br />
            <div class="form-group row">
                <label asp-for="Customer" class="col-sm-2 col-form-label">Client Name:</label>
                @if(title == "Create")
                {
                    <div class="col-sm-10">
                        <select asp-for="CustomerId" class="form-control" asp-items="@ViewBag.CustomerId">
                  
                        </select>
                        <span asp-validation-for="Customer" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="col-sm-10">
                        <input asp-for="CustomerId" class="form-control" asp-items="@ViewBag.CustomerId" />
                        <span asp-validation-for="Customer" class="text-danger"></span>
                    </div>
                }
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="Product" class="col-sm-2 col-form-label">Product:</label>
                @if(title == "Create")
                {
                    <div class="col-sm-10">
                        <select asp-for="ProductId" class="form-control" asp-items="@ViewBag.ProductId"></select>
                        <span asp-validation-for="Product" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="col-sm-10">
                        <input asp-for="ProductId" class="form-control" asp-items="@ViewBag.ProductId" />
                        <span asp-validation-for="Product" class="text-danger"></span>
                    </div>
                }
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="IncidentTitle" class="col-sm-2 col-form-label">Title:</label>
                <div class="col-sm-10">
                    <input asp-for="IncidentTitle" class="form-control" />
                    <span asp-validation-for="IncidentTitle" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="IncidentDescription" class="col-sm-2 col-form-label">Description:</label>
                <div class="col-sm-10">
                    <input asp-for="IncidentDescription" class="form-control" />
                    <span asp-validation-for="IncidentDescription" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="Technician" class="col-sm-2 col-form-label">Technician:</label>
                @if(title == "Create")
                {
                    <div class="col-sm-10">
                        <select asp-for="TechnicianId" class="form-control" asp-items="@ViewBag.TechnicianId"></select>
                        <span asp-validation-for="Technician" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="col-sm-10">
                        <input asp-for="TechnicianId" class="form-control" asp-items="@ViewBag.TechnicianId" />
                        <span asp-validation-for="Technician" class="text-danger"></span>
                    </div>
                }
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="IncidentDescription" class="col-sm-2 col-form-label">Description:</label>
                <div class="col-sm-10">
                    <input asp-for="IncidentDescription" class="form-control" />
                    <span asp-validation-for="IncidentDescription" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="IncidentDateOpened" class="col-sm-2 col-form-label">Date Opened:</label>
                <div class="col-sm-10">
                    <input asp-for="IncidentDateOpened" class="form-control" />
                    <span asp-validation-for="IncidentDateOpened" class="text-danger"></span>
                </div>
            </div>

            <br />
            <div class="form-group row">
                <label asp-for="IncidentDateClosed" class="col-sm-2 col-form-label">Date Closed:</label>
                <div class="col-sm-10">
                    <input asp-for="IncidentDateClosed" class="form-control" />
                </div>
            </div>
                


            <br />
            <div class="form-group">
                <input type="submit" value="@ViewData["Title"]" class="btn btn-success" />
                @if(title == "Create")
                {
                 <input type="reset" class="btn btn-danger" />   
                }

            </div>
        </form>
    </div>
</div>

<br />
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to Incidents List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comp2139-Assignment1/Comp2139-Assignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sports</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sports.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sports</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Technicians" asp-action="Index">Technicians</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Incidents" asp-action="Index">Incidents</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Registration</a>        <!--Registration for what?-->
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sports
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>